export const STATE_VALUE_CHANGE = 'STATE_VALUE_CHANGE';
export const RIEW_RENDER = 'RIEW_RENDER';
export const RIEW_UNMOUNT = 'RIEW_UNMOUNT';
export const CANCEL_EFFECT = 'CANCEL_EFFECT';

export const QUEUE_START = 'QUEUE_START';
export const QUEUE_END = 'QUEUE_END';
export const QUEUE_STEP_IN = 'QUEUE_STEP_IN';
export const QUEUE_STEP_OUT = 'QUEUE_STEP_OUT';
export const QUEUE_SET_STATE_VALUE = 'QUEUE_SET_STATE_VALUE';
